### ISSUE TITLE
Tests failure installing on Xubuntu via Panda

### ISSUE THREAD

**Issue by Von-Cheam** [ab5tract/Terminal-Print#17]
If there's anything you'd like me to try, or any information about my system you'd like, please do let me know!

Terminal output:
```shell
$ panda install Terminal::Print
==> Fetching Terminal::Print
==> Building Terminal::Print
==> Testing Terminal::Print
t/00-basics.t .. ok

    # Failed test 'Can print the current grid'
    # at t/10-grid.t line 27
    # Cannot invoke this object (REPR: Null; VMNull)

    # Failed test 'Can print a screen full of multi colored hearts'
    # at t/10-grid.t line 34
    # Cannot invoke this object (REPR: Null; VMNull)
    # Looks like you failed 2 tests of 3

# Failed test 'Basic screen of hearts can be generated in the expected fashion'
# at t/10-grid.t line 20
# Looks like you failed 1 test of 1
t/10-grid.t .... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
t/11-golf.t .... ok

Test Summary Report
-------------------
t/10-grid.t  (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=3, Tests=6,  4 wallclock secs ( 0.02 usr  0.00 sys +  3.06 cusr  0.23 csys =  3.31 CPU)
Result: FAIL
test stage failed for Terminal::Print: 0
  in method install at /home/voncheam/.rakudobrew/moar-nom/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 186
  in method resolve at /home/voncheam/.rakudobrew/moar-nom/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 263
  in sub MAIN at /home/voncheam/.rakudobrew/moar-nom/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 20
  in block <unit> at /home/voncheam/.rakudobrew/moar-nom/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 165


Failure Summary
----------------
Terminal::Print(
	*test stage failed for Terminal::Print: 0)
```

**Comment by ab5tract** [comment]
Thanks for reporting.

Which version of rakudo are you using?

**Comment by Von-Cheam** [comment]
```shell
$ perl6 --version
This is Rakudo version 2016.11-142-g16fbd71 built on MoarVM version 2016.11-25-g4be6b38
implementing Perl 6.c.
$ panda info panda
panda (version 2016.02 available, 2016.02 installed)
```

**Comment by ab5tract** [comment]
Strange, it is installing fine for me with an up to date build.

What's your `$TERM` env var set to?

**Comment by Von-Cheam** [comment]
```shell
$ echo $TERM
xterm
$ ls /lib/terminfo/x/
xterm  xterm-256color  xterm-color  xterm-debian
xterm-mono xterm-r5  xterm-r6  xterm-vt220  xterm-xfree86
```
Hmm. If nobody else is reporting problems, maybe it's my system? Pretty much vanilla Xubuntu 16.04 install, but I do have a Perl6 ncurses wrapper package installed:
```shell
$ panda list --installed
App::Mi6               [installed] 
File::Directory::Tree  -dependency-
File::Find             -dependency-
File::Temp             -dependency-
File::Which            -dependency-
JSON::Fast             -dependency-
JSON::Pretty           -dependency-
JSON::Tiny             -dependency-
NCurses                [installed] 
OO::Monitors           -dependency-
Pod::To::Markdown      -dependency-
Shell::Command         -dependency-
Terminal::ANSIColor    [installed] 
panda                  [installed] 
```
Thanks very much for looking into this, anyhow!

**Comment by ab5tract** [comment]
Darn, that means it is not the obvious issue (`$TERM` value missing from the whitelist).

Can you try running some examples via `panda look` or by cloning the repo?

`perl6 -Ilib examples/matrix-ish.p6`, for instance.

Perhaps a stack trace will help illuminate.

**Comment by Von-Cheam** [comment]
Okay. Going to reproduce my whole procedure here, because I'm not exactly an expert, and I may be going wrong somehwere:
```shell
$ cd /tmp
$ git clone https://github.com/ab5tract/Terminal-Print
Cloning into 'Terminal-Print'...
remote: Counting objects: 1041, done.
remote: Total 1041 (delta 0), reused 0 (delta 0), pack-reused 1041
Receiving objects: 100% (1041/1041), 169.97 KiB | 98.00 KiB/s, done.
Resolving deltas: 100% (495/495), done.
Checking connectivity... done.
$ cd Terminal-Print/
$ perl6 -Ilib examples/matrix-ish.p6
```
Running that last command clears the terminal, vanishes the cursor and prints this error message:
```
===SORRY!===
Cannot invoke this object (REPR: Null; VMNull)
```
Running this command `$ perl6 examples/alphabetics.p6` also clears the terminal and vanishes the cursor, but prints this stack trace:
```
Cannot invoke this object (REPR: Null; VMNull)
  in block  at /home/voncheam/.rakudobrew/moar-nom/install/share/perl6/site/sources/B7DF632EBAC65169FAE1AF8BFB774E9775D8BA37 (OO::Monitors) line 33
  in block  at /home/voncheam/.rakudobrew/moar-nom/install/share/perl6/site/sources/B7DF632EBAC65169FAE1AF8BFB774E9775D8BA37 (OO::Monitors) line 30
  in any enter at gen/moar/Metamodel.nqp line 3990
  in method print-cell at /tmp/Terminal-Print/lib/Terminal/Print/Grid.pm6 (Terminal::Print::Grid) line 61
  in any call_with_capture at gen/moar/Metamodel.nqp line 3892
  in block  at /home/voncheam/.rakudobrew/moar-nom/install/share/perl6/site/sources/B7DF632EBAC65169FAE1AF8BFB774E9775D8BA37 (OO::Monitors) line 31
  in block  at /home/voncheam/.rakudobrew/moar-nom/install/share/perl6/site/sources/B7DF632EBAC65169FAE1AF8BFB774E9775D8BA37 (OO::Monitors) line 25
  in any enter at gen/moar/Metamodel.nqp line 3990
  in method print-cell at /tmp/Terminal-Print/lib/Terminal/Print/Grid.pm6 (Terminal::Print::Grid) line 67
  in any call_with_capture at gen/moar/Metamodel.nqp line 3892
  in block  at /home/voncheam/.rakudobrew/moar-nom/install/share/perl6/site/sources/B7DF632EBAC65169FAE1AF8BFB774E9775D8BA37 (OO::Monitors) line 31
  in block  at /home/voncheam/.rakudobrew/moar-nom/install/share/perl6/site/sources/B7DF632EBAC65169FAE1AF8BFB774E9775D8BA37 (OO::Monitors) line 25
  in any enter at gen/moar/Metamodel.nqp line 3990
  in method print-cell at /tmp/Terminal-Print/lib/Terminal/Print.pm6 (Terminal::Print) line 211
  in block  at examples/alphabetics.p6 line 14
  in block <unit> at examples/alphabetics.p6 line 13
```

**Comment by ab5tract** [comment]
Okay, that's just weird. It looks like it might be `OO::Monitors` that is actually failing somehow. I suppose it passed its own tests, though, as it installed cleanly...

Are you running a 32-bit OS by any chance?

**Comment by Von-Cheam** [comment]
Nope, 'fraid not!
```shell
$ uname -a
Linux CheamBox-2 4.4.0-53-generic #74-Ubuntu SMP
Fri Dec 2 15:59:10 UTC 2016
x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Xliff** [comment]
This is exactly the issue I had with OO::Monitors.

You can fix it by cloning OO::Monitors, issuing this command:

```
git reset --hard b05961683ff7077663894a146cc64326b2487f55
```

And then reinstalling with

```
panda install --force .
```

Hope that helps.

**Comment by Von-Cheam** [comment]
Thanks @Xliff - that's worked, and now Terminal::Print passes tests and installs. However, trying to run any of the examples gives the following error:
```shell
$ perl6 alphabetics.p6
===SORRY!===
Could not find Terminal::Print::Widget at line 62 in:
    /home/voncheam/.perl6
    /home/voncheam/.rakudobrew/moar-nom/install/share/perl6/site
    /home/voncheam/.rakudobrew/moar-nom/install/share/perl6/vendor
    /home/voncheam/.rakudobrew/moar-nom/install/share/perl6
    CompUnit::Repository::AbsolutePath<72095920>
    CompUnit::Repository::NQP<66553520>
    CompUnit::Repository::Perl5<66553560>
```
Should I open a new issue for this, or could it be related?

**Comment by japhb** [comment]
Von-Cheam: This should now be fixed; the META6.json was out of date and has now been corrected.

**Comment by ronaldxs** [comment]
Getting exactly the same errors from grid.t on installation.  Tried the git reset on OO::Monitors suggestion by Xliff and didn't fix the problem.  Running examples/alphabetics.p6 gives similar output to Von-cheam.

```
ron@ron-laptop:~/my-perl6/oo-monitors$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
ron@ron-laptop:~/my-perl6/oo-monitors$ perl6 --version
This is Rakudo version 2016.12-91-g3282813 built on MoarVM version 2016.12-6-g65acd55
implementing Perl 6.c.
ron@ron-laptop:~/my-perl6/oo-monitors$ echo $TERM
xterm
```

**Comment by japhb** [comment]
ronaldxs, does https://github.com/ab5tract/Terminal-Print/issues/32#issuecomment-269165344 work for you?  ugexe describes a different way of getting back to a working state.

**Comment by ronaldxs** [comment]
Yes that worked.  From the output of the "zef uninstall" it looks like I may have had both <1.0> and <1.1> versions of OO::Monitors installed.

**Comment by Von-Cheam** [comment]
Okay, I've just reinstalled via Panda and everything's working, now. Thanks, all.

**Comment by japhb** [comment]
Looks like this one should have been closed after the last comment from Von-Cheam.
